spring.application.name=face-analyze
server.port=8085

# ActiveMQ
spring.activemq.broker-url=${SPRING_ACTIVEMQ_BROKER_URL:tcp://localhost:61616}

# URLs par defaut (Local)
ms.cache.url=http://localhost:8083/cache/media/{requestId}

hf.token=${HF_TOKEN}
