# --- CONFIGURATION DU SERVEUR ---
server.port=8080

# --- CONFIGURATION ACTIVEMQ ---
# URL du broker (soit local, soit via variable d'environnement Docker)
spring.activemq.broker-url=${ACTIVEMQ_URL:tcp://localhost:61616}
spring.activemq.user=admin
spring.activemq.password=admin

# Nom des queues
application.queue.avatar=avatar-queue
activemq.queue.name=Notification-queue


# --- CONFIGURATION MICROSERVICES ---
# URLs par defaut pour le local (ecrasees par Docker)
ms.avatar.url=${MS_AVATAR_URL:http://localhost:8081/avatar/process}
ms.cache.url=${MS_CACHE_URL:http://localhost:8083/cache/media/upload}

# --- UPLOAD FICHIERS ---
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# --- CONFIGURATION BDD ---
# On enleve DB_CLOSE_ON_EXIT=FALSE qui entre en conflit avec AUTO_SERVER
spring.datasource.url=jdbc:h2:file:./data/transformed_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate se charge de creer la table si elle n'existe pas
spring.jpa.hibernate.ddl-auto=update

# Configuration de la Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Optionnel : autoriser l'acces a la console depuis l'exterieur (si docker)
spring.h2.console.settings.web-allow-others=true