spring.application.name=prompt
server.port=8084

# ActiveMQ
spring.activemq.broker-url=tcp://activemq:61616
spring.activemq.user=admin
spring.activemq.password=admin
activemq.queue.name=Notification-queue