spring.application.name=avatar
server.port=8081

# Autoriser les gros fichiers sur ce service aussi
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ActiveMQ
spring.activemq.broker-url=${SPRING_ACTIVEMQ_BROKER_URL:tcp://localhost:61616}

# URLs par defaut (Local)
ms.image.url=http://localhost:8086/api/transform
ms.prompt.url=http://localhost:8084/prompt/format
ms.face.url=http://localhost:8085/face/process