spring.application.name=Ms-Image
server.port=8086

# ActiveMQ
spring.activemq.broker-url=${SPRING_ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
# Fooocus API
fooocus.api.url=${FOOOCUS_API_URL:http://tp.cpe.fr:8088}

